name: ESP-IDF CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32, esp32c3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.2
          target: ${{ matrix.target }}
          skip_build: true

      - name: Build project
        run: |
          mkdir -p build_${{ matrix.target }}
          idf.py -B build_${{ matrix.target }} \
            -DIDF_TARGET=${{ matrix.target }} \
            -DSDKCONFIG=sdkconfig.${{ matrix.target }} \
            build

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-firmware
          path: build_${{ matrix.target }}/
          retention-days: 7
