name: ESP-IDF CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32, esp32c3]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.2
          target: ${{ matrix.target }}

      - name: Prepare sdkconfig
        run: |
          if [ -f "sdkconfig.${{ matrix.target }}" ]; then
            echo "Restoring sdkconfig.${{ matrix.target }}"
            cp sdkconfig.${{ matrix.target }} sdkconfig
          else
            echo "No sdkconfig.${{ matrix.target }} found, will generate new one"
          fi

      - name: Set target
        run: |
          idf.py set-target ${{ matrix.target }}

      - name: Clean build folder
        run: |
          idf.py -B build_${{ matrix.target }} fullclean

      - name: Build project
        run: |
          idf.py -B build_${{ matrix.target }} build

      - name: Save sdkconfig for this target
        run: |
          cp sdkconfig sdkconfig.${{ matrix.target }}

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-firmware
          path: build_${{ matrix.target }}/
          retention-days: 7
